/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cherish_component_jni_NativeQualityScore */

#ifndef _Included_cherish_component_jni_NativeQualityScore
#define _Included_cherish_component_jni_NativeQualityScore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cherish_component_jni_NativeQualityScore
 * Method:    GetQualityScore
 * Signature: ([BIIIIIIIILjava/lang/String;)Lcherish/component/jni/QualityImage;
 */
JNIEXPORT jobject JNICALL Java_cherish_component_jni_NativeQualityScore_GetQualityScore
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
