package cherish.component.jpa

// Generated Mar 25, 2019 9:54:31 AM by Stark Activerecord generator 4.3.1.Final

import java.util.Date
import javax.persistence.{Column, Entity, Id, Table}

import cherish.component.database.jpa.{ActiveRecord, ActiveRecordInstance}

/**
  * Personinfo generated by stark activerecord generator
  */
object PersonLevelScore extends ActiveRecordInstance[PersonLevelScore]

@Entity
@Table(name = "person_level_score")
class PersonLevelScore extends ActiveRecord {

  @Id
  @Column(name = "id", unique = true, nullable = false, length = 32)
  var id: java.lang.String = _
  @Column(name = "person_level")
  var level: String = _
  @Column(name = "rm")
  var rm: Int = _
  @Column(name = "rs")
  var rs: Int = _
  @Column(name = "rz")
  var rz: Int = _
  @Column(name = "rh")
  var rh: Int = _
  @Column(name = "rx")
  var rx: Int = _
  @Column(name = "lm")
  var lm: Int = _
  @Column(name = "ls")
  var ls: Int = _
  @Column(name = "lz")
  var lz: Int = _
  @Column(name = "lh")
  var lh: Int = _
  @Column(name = "lx")
  var lx: Int = _
  @Column(name = "input_time")
  var inputTime: Date = _

  def this(id: java.lang.String) {
    this()
    this.id = id
  }

  def this(id: java.lang.String,level:String, rm: java.lang.Integer, rs: java.lang.Integer, rz: java.lang.Integer, rh: java.lang.Integer, rx: java.lang.Integer, lm: java.lang.Integer, ls: java.lang.Integer, lz: java.lang.Integer, lh: java.lang.Integer, lx: java.lang.Integer, inputTime:Date) {
    this()
    this.id = id
    this.rm = rm
    this.rs = rs
    this.rz = rz
    this.rh = rh
    this.rx = rx
    this.lm = lm
    this.ls = ls
    this.lz = lz
    this.lh = lh
    this.lx = lx
    this.inputTime = inputTime
  }
}


